version: '3'

services:
  ### Testing email settings
  email:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-10-november-2019/final-projects/razzpay
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'python manage.py send_mail'
    #command: "tail -f /dev/null"
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    depends_on:
      - postgres
      - backend
  #####


  postgres:
    image: postgres:latest
    ports:
      - '5555:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-10-november-2019/final-projects/razzpay
    restart: always
    env_file:
      - ./envs/dev.env
#    command: "sh #!/bin/bash"
    command: "tail -f /dev/null"
    ports:
      - '8000:8000'
      - '4777:22'
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files


  # no need for nginx and gunicorn for local development environment (see docker-compose.deploy.yml)



#version: '3'
#
#services:
#  postgres:
#    image: postgres:latest
#    ports:
#      - '5432:5432'
#    env_file:
#      - ./envs/dev.env
#    volumes:
#      - postgres:/var/lib/postgresql/data
#
volumes:
  postgres:
