name: django-models-livecoding
dependencies:
  - python=3.6
  - psycopg2
  - pip:
      - Django==3.0
      - djangorestframework==3.10.3
      - markdown==3.1.1
      - django-filter==2.2.0
      - djangorestframework-simplejwt==4.3.0
      - Pillow==6.2.1
      - flake8
      - gunicorn
