name: razzpay
dependencies:
  - python=3.6
  - psycopg2
  - pip:
      - Django==3.0
      - djangorestframework==3.10.3
      - markdown==3.1.1
      - django-filter==2.2.0
      - djangorestframework-simplejwt==4.3.0
     # - coreapi==2.3.3
      - Pillow==6.2.1
      - flake8
      - gunicorn
      - django-cors-headers
      - pywebcopy
      - beautifulsoup4==4.7.1
      - django-cors-headers
      - webpreview==1.6.0
      - django-extensions==2.2.5
      - django-fullurl==1.0
      - weasyprint
      - django-weasyprint

